//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQ_Queries1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Dbo_EntityFrameworkDemoEntities : DbContext
    {
        public Dbo_EntityFrameworkDemoEntities()
            : base("name=Dbo_EntityFrameworkDemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Clups> Tbl_Clups { get; set; }
        public virtual DbSet<Tbl_CourseGrades> Tbl_CourseGrades { get; set; }
        public virtual DbSet<Tbl_Lessons> Tbl_Lessons { get; set; }
        public virtual DbSet<Tbl_Student> Tbl_Student { get; set; }
    }
}
