//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQ_Queries1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CourseGrades
    {
        public int CGID { get; set; }
        public Nullable<int> Student { get; set; }
        public Nullable<int> Lesson { get; set; }
        public Nullable<short> CourseGrade1 { get; set; }
        public Nullable<short> CourseGrade2 { get; set; }
        public Nullable<short> CourseGrade3 { get; set; }
        public Nullable<decimal> Average { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Tbl_Lessons Tbl_Lessons { get; set; }
        public virtual Tbl_Student Tbl_Student { get; set; }
    }
}
